/**
 * Turn a Wialon geofence KML export into the SQL that imports it.
 *
 *   node --experimental-strip-types scripts/geofence-kml-import.mts \
 *        Geofences.kml > /tmp/geofences.sql
 *
 * Then run the output against the database. It is idempotent: every
 * write goes through upsert_site_geofence, which replaces a site's
 * existing polygon rather than adding a second one.
 *
 * WHY IT EMITS SQL INSTEAD OF WRITING ROWS
 *
 * The zone is only half the match; the other half is which of the 125
 * construction_sites it belongs to, and THAT decision is made against
 * the live table, in Postgres. A local copy of the site coordinates
 * would be a second source of truth for the one fact the whole import
 * turns on, and a stale one picks the wrong site silently. So this
 * script contributes only what the KML actually contains — names,
 * outlines, centroids — and the ranking happens where the sites live.
 *
 * WHAT IT REFUSES TO IMPORT (the review list the SQL prints at the end)
 *
 *   no-site-within-5km    a genuinely new client, or a site whose
 *                         stored coordinate is wrong. Either way a
 *                         person has to look.
 *   ambiguous-two-sites   the nearest site is more than 40% as far as
 *                         the runner-up. Usually two sites sharing one
 *                         stored coordinate to the digit.
 *   site-already-claimed  a nearer zone already took this site. A site
 *                         has ONE geofence — upsert_site_geofence
 *                         deletes before it inserts — so importing
 *                         both would silently keep only the last.
 *   invalid-geometry      the ring crosses itself. PostGIS rejects it
 *                         and point-in-polygon on one is unreliable.
 *   oversize              bigger than SITE_FENCE_MAX_HECTARES. Time in
 *                         zone is measured by containment, so a fence
 *                         wide enough to drive across satisfies the
 *                         unloading rule without anyone stopping. Added
 *                         2026-09-03 after four such fences were found
 *                         already live, the worst 6.5 km across.
 *
 * The 2026-08-31 run of the real 1044-zone export: 138 prefixed, 106
 * imported outright, 32 held back across the first four buckets. That
 * run predates the size check. Five of those 138 exceed the size limit:
 * four were imported and are live fences today (4258, 1432, 858 and
 * 276 ha — the sites ADRAR, CHIALI EL MENIA, FAUCON BLEU ADRAR and
 * HASSI DELAA), and the fifth, the 145 547 ha M'Guiden pipeline route,
 * was already held back as no-site-within-5km. So re-running with this
 * check holds back four zones it previously imported, and the four live
 * fences stay wrong until they are redrawn in Wialon — the tail query
 * below reports them on every run so they are not forgotten.
 */
import { readFileSync } from "node:fs";
import {
  parseGeofenceKml,
  ringCentre,
  ringToPolygonWkt,
  ringSelfIntersects,
  SITE_FENCE_MAX_HECTARES,
} from "../src/lib/kml/geofenceKml.ts";

// Kept in step with geofenceKml.ts by hand — see the comments there for
// why each allowance exists. Both are real names from the export.
const AMOUDA_PREFIX = /^\s*ciment(?:e|et)?r?ie\s+amouda\s*[-–—]?\s*(?:client\s*)?/i;
const FACTORY_ZONE = /usine\s+amouda/i;

const path = process.argv[2];
if (!path) {
  console.error("usage: geofence-kml-import.mts <export.kml>");
  process.exit(1);
}

const zones = parseGeofenceKml(readFileSync(path, "utf8"));
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const rows: string[] = [];
const dropped: string[] = [];
for (const z of zones) {
  if (FACTORY_ZONE.test(z.name) || !AMOUDA_PREFIX.test(z.name)) continue;
  // Wialon exports 10 decimal places — sub-millimetre, on a boundary
  // hundreds of metres across that somebody drew by hand. Six (~11cm)
  // carries the whole shape and halves the payload.
  const wkt = ringToPolygonWkt(z.ring)?.replace(/-?\d+\.\d+/g, (n) => String(+(+n).toFixed(6)));
  const c = ringCentre(z.ring);
  if (!wkt || !c) { dropped.push(z.name); continue; }
  rows.push(
    `(${rows.length + 1},${q(z.name)},${+c[0].toFixed(6)},${+c[1].toFixed(6)},` +
    `${ringSelfIntersects(z.ring)},${q(wkt)})`
  );
}

for (const name of dropped) console.error(`  no usable geometry, skipped: ${name}`);
console.error(`${zones.length} zones in export, ${rows.length} carry the Amouda prefix`);

// The staging table lives in public because PostgREST is the only way
// in, and it is dropped at the end of the same script for exactly that
// reason: an un-RLS'd table in public is readable by anon while it
// exists. Nothing between the CREATE and the DROP is interactive.
const out = `-- Generated by scripts/geofence-kml-import.mts from ${path.split("/").pop()}
begin;

drop table if exists public._zone_import cascade;
create table public._zone_import (
  idx int primary key,
  zone_name text not null,
  clat double precision not null,
  clng double precision not null,
  self_x boolean not null,
  wkt text not null
);

insert into public._zone_import (idx,zone_name,clat,clng,self_x,wkt) values
${rows.join(",\n")};

-- Nearest site, and how far the runner-up was. A match at 0.3km with
-- the next site 115km off is certain; one at 4km with the next at 5km
-- is a coin toss whatever the names look like.
create view public._zone_match as
with g as (
  select z.idx, z.zone_name, z.self_x, z.wkt,
         ST_SetSRID(ST_GeomFromText(z.wkt), 4326) as geom,
         ST_SetSRID(ST_MakePoint(z.clng, z.clat), 4326)::geography as cg
  from public._zone_import z
),
r as (
  select g.idx, s.id as site_id, s.name as site_name, s.client as site_client,
         ST_Distance(g.cg, ST_SetSRID(ST_MakePoint(s.lng, s.lat), 4326)::geography) / 1000.0 as km,
         row_number() over (partition by g.idx
           order by ST_Distance(g.cg, ST_SetSRID(ST_MakePoint(s.lng, s.lat), 4326)::geography)) as rn
  from g cross join public.construction_sites s
)
select g.idx, g.zone_name, g.self_x, g.wkt,
       ST_IsValid(g.geom) as valid,
       ST_Area(g.geom::geography) / 1e6 as area_km2,
       b.site_id, b.site_name, b.site_client,
       round(b.km::numeric, 3) as km,
       round(u.km::numeric, 3) as runner_up_km,
       round((b.km / nullif(u.km, 0))::numeric, 3) as ratio
from g
join r b on b.idx = g.idx and b.rn = 1
left join r u on u.idx = g.idx and u.rn = 2;

create view public._zone_plan as
with eligible as (
  -- The size test belongs here as well as in the verdict below: an
  -- oversize zone that still "claims" its site would push a smaller,
  -- better-drawn zone for the same site into site-already-claimed and
  -- hold back the good one instead of the bad one.
  select m.*, (m.valid
               and m.area_km2 * 100 <= ${SITE_FENCE_MAX_HECTARES}
               and m.km <= 5
               and (m.ratio is null or m.ratio <= 0.4)) as ok
  from public._zone_match m
),
ranked as (
  select e.*,
         case when e.ok then row_number() over (
           partition by case when e.ok then e.site_id end order by e.km) end as claim_rank
  from eligible e
)
select r.*,
       case
         when not r.valid      then 'invalid-geometry'
         when r.area_km2 * 100 > ${SITE_FENCE_MAX_HECTARES} then 'oversize'
         when r.km > 5         then 'no-site-within-5km'
         when r.ratio > 0.4    then 'ambiguous-two-sites'
         when r.claim_rank > 1 then 'site-already-claimed'
         else 'import'
       end as verdict
from ranked r;

select count(*) as imported from (
  select public.upsert_site_geofence(p.site_id, p.site_name, p.wkt, null)
  from public._zone_plan p where p.verdict = 'import'
) t;

-- Everything a person still has to decide.
select verdict, idx, site_name, km, runner_up_km,
       round(area_km2::numeric, 3) as area_km2,
       regexp_replace(zone_name, '^\\s*ciment(e|et)?r?ie\\s+amouda\\s*[-–—]?\\s*(client\\s*)?', '', 'i') as zone
from public._zone_plan where verdict <> 'import'
order by verdict, km nulls last;

-- Fences ALREADY in the table that would fail the size check. The
-- verdict above only screens what this run is importing, and the four
-- found on 2026-09-03 were imported before the check existed, so every
-- run re-reports them until someone redraws them in Wialon.
select s.name, s.client,
       round((ST_Area(g.polygon::geography) / 10000)::numeric, 1) as hectares
from public.geofences g
join public.construction_sites s on s.id = g.site_id
where g.kind = 'site' and g.polygon is not null
  and ST_Area(g.polygon::geography) / 10000 > ${SITE_FENCE_MAX_HECTARES}
order by hectares desc;

-- Sites left without a polygon: they fall back to a 300m radius.
select s.name, s.client from public.construction_sites s
where not exists (select 1 from public.geofences g where g.site_id = s.id and g.kind = 'site')
order by s.name;

-- A flipped lat/lng puts Algeria in the Indian Ocean and nothing else
-- catches it, so assert the bounding box rather than trusting the flip.
select count(*) as invalid,
       count(*) filter (where ST_YMin(polygon) < 18 or ST_YMax(polygon) > 38
                          or ST_XMin(polygon) < -10 or ST_XMax(polygon) > 12) as outside_algeria
from public.geofences where polygon is not null and not ST_IsValid(polygon);

drop view public._zone_plan;
drop view public._zone_match;
drop table public._zone_import;

commit;
`;

process.stdout.write(out);
